### ISSUE TITLE
heidelberg has_fee shall be set

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [ParkenDD/parkapi-sources-v3#116]
If a parking site contains a "pricing" array, the attribute "has_fee" shall be set.

**Comment by the-infinity** [comment]
I guess you mean: if the `prices` value has a length of 0, `has_fee` should be set to false, otherwise to true, instead of just setting it always to true which is the situation now? If yes: implemented in https://github.com/ParkenDD/parkapi-sources-v3/pull/126

**Comment by the-infinity** [comment]
Then it's done.
