### ISSUE TITLE
wrong coordinates for karlsruhe and karlsruhe_bike

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [ParkenDD/parkapi-sources-v3#47]
karlsruhe and karlsruhe_bike swapped lat and lon. further, longitude is shiftes from Germany to France:

        {
            "source_id": 4,
            "original_uid": "78",
            "name": "Scheck-In-Center",
            "address": "Marstallstraße 18, 76227 Karlsruhe",
            "purpose": "CAR",
            "has_realtime_data": false,
            "static_data_updated_at": "2023-12-31T00:00:00Z",
            _"lat": "3.1699124",
            "lon": "49.4830962",_
            "id": 372,
            "created_at": "2024-05-31T05:47:58Z",
            "modified_at": "2024-05-31T05:47:58Z",
            "external_identifiers": [],
            "tags": []
        },

**Comment by the-infinity** [comment]
Oh, they have a strange coordinate system as their default. But as Karlsruhe uses a Geoserver, it's possible to just change the coordinate system to WSG84.
