### ISSUE TITLE
Add Goldbeck Opening times

### ISSUE THREAD

**Issue by the-infinity** [ParkenDD/parkapi-sources-v3#77]
At https://github.com/ParkenDD/parkapi-sources-v3/pull/68 , we decided to merge Goldbecks data input ignoring the broken opening times. The opening times should be added later.

**Comment by the-infinity** [comment]
The opening times were handled at the parent function `map_row_to_parking_site_dict` you overwrote without calling the parent. But, if you use the parent, the whole thing crashes because of a lot of invalid data, neither `closed` nor `1900-01-01 00:00:00` is a valid time. That why this will need more work (and in my opinion, at least `1900-01-01 00:00:00` has to be fixed by Goldbeck / before the upload, that's just broken).

**Comment by AbdullahiFatola** [comment]
Ok now I understand. Someone in our team collected the data manually from this [Goldbeck website](https://www.goldbeck-parking.de/parkplatzsuche#/). So we can fix the data internally according to the Information on the website.

**Comment by AbdullahiFatola** [comment]
How would you suggest to fix this? I tried just now to input ```24:00:00``` to replace ```1900-01-01 00:00:00```  in the excel file but it keeps formatting it to ```1900-01-01 00:00:00```

For ```closed``` would it be better to leave the cell empty?
