### ISSUE TITLE
herrenberg converter fills fee_description attribute with opening times

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [ParkenDD/parkapi-sources-v3#99]
herrenberg produces fee_descriptions like:
        {
            "source_id": 6,
            "original_uid": "herrenbergkurzzeitparkplaetzebahnhofstrasse",
            "name": "Kurzzeitparkplätze Bahnhofstraße",
            "operator_name": "Stadt Herrenberg",
            "public_url": "https://stadtwerke.herrenberg.de/oepnv-parken/parken/sicher-und-zentral-parken/parkhaeuser-und-parkgebuehren/kurzzeitparkplaetze-bahnhofstrasse/",
            "address": "71083 Herrenberg",
            "type": "ON_STREET",
            "purpose": "CAR",
            **"fee_description": "Mo-Fr 08:00-20:00; Sa 08:00-14:00; PH off",**
            "has_fee": true,
            "has_realtime_data": false,
            "static_data_updated_at": "2024-08-16T06:32:02Z",
            "lat": "48.5936340",
            "lon": "8.8632470",
            "capacity": 47,
            "id": 664,
            "created_at": "2024-08-16T06:33:35Z",
            "modified_at": "2024-08-16T06:33:35Z"
        }
These data should be mapped to the opening_hours attribute.

**Comment by the-infinity** [comment]
Sadly, that's not opening hours, but actually the times when there is a fee. In the original dataset, it's called `fee_hours`. But: We could remove it as it's not really human readable.

**Comment by ThorstenFroehlinghaus** [comment]
Yes, please remove the mapping of fee_hours as it is misleading.

**Comment by the-infinity** [comment]
Done: https://github.com/ParkenDD/parkapi-sources-v3/pull/134
